### PR TITLE
Implement betamax

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
If you want to test locally, you can just ```rm openprovider/tests/fixtures/cassettes/*.json``` and it will recreate them.

**Comment by wandernauta** [comment]
Ah, okay. :+1: from me, I'll leave it up to you if you want to do anything with the decorator idea.

**Comment by ekohl** [comment]
I will play with it to see how easy it is. I can imagine that it won't always work (do the same request twice but a create in between), but in most cases it can save a lot of code.

**Comment by ekohl** [comment]
Now with decorator where possible. Couldn't get it to work easily on multiple requests (though the docs suggest it should work), but this is already much cleaner.

**Comment by ekohl** [comment]
http://betamax.readthedocs.org/en/latest/api.html#betamax.configure.Configuration suggests the ```match_requests_on``` parameter which defaults to either ```['method', 'uri']``` or ```['uri']``` (not sure which one) but both don't work because we always ```POST``` to the same URI. I consider that future work :)

**Comment by wandernauta** [comment]
Matching on ['body'] should work, though.

**Comment by ekohl** [comment]
It should, but in the concrete case of test_domain it wouldn't help because need the control. Still, I'll try to bundle into 2 cassettes instead of 5.

**Comment by ekohl** [comment]
Correction: it would be different since the username is part of the body.

**Comment by wandernauta** [comment]
Hmm, fair point.

**Comment by ekohl** [comment]
I rewrote it to also mark the secundary variables as private, but couldn't really make it much cleaner since you have two sessions going. If you really want to, I suppose you can.

**Comment by wandernauta** [comment]
:+1: :+1:

**Pull request merged**
